// <auto-generated />
using System;
using Leavemanagement.Repository.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leavemanagement.Repository.Migrations
{
    [DbContext(typeof(LeaveManagementsDbContext))]
    [Migration("20260315052521_addApproval")]
    partial class addApproval
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Leavemanagement.Repository.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Leavemanagement.Repository.Entity.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalLeaveCount")
                        .HasColumnType("int");

                    b.Property<int>("UsedLeaveCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("leaveBalances");
                });

            modelBuilder.Entity("Leavemanagement.Repository.Entity.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdminApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HRId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HRapprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ManagerapprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalLeaveDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("HRId");

                    b.HasIndex("ManagerId");

                    b.ToTable("leaveRequests");
                });

            modelBuilder.Entity("Leavemanagement.Repository.Entity.ProofMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ProofPhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ProofMappings");
                });

            modelBuilder.Entity("Leavemanagement.Repository.Entity.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Leavemanagement.Repository.Entity.UserMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserMappings");
                });

            modelBuilder.Entity("Leavemanagement.Repository.Entity.LeaveBalance", b =>
                {
                    b.HasOne("Leavemanagement.Repository.Entity.Employee", "Employees")
                        .WithMany("leaveBalances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Leavemanagement.Repository.Entity.LeaveRequest", b =>
                {
                    b.HasOne("Leavemanagement.Repository.Entity.Employee", "Admins")
                        .WithMany("leaveRequestsAdmin")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Leavemanagement.Repository.Entity.Employee", "Employees")
                        .WithMany("leaveRequestsEmployee")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Leavemanagement.Repository.Entity.Employee", "HRs")
                        .WithMany("leaveRequestsHr")
                        .HasForeignKey("HRId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Leavemanagement.Repository.Entity.Employee", "Managers")
                        .WithMany("leaveRequestsManager")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admins");

                    b.Navigation("Employees");

                    b.Navigation("HRs");

                    b.Navigation("Managers");
                });

            modelBuilder.Entity("Leavemanagement.Repository.Entity.ProofMapping", b =>
                {
                    b.HasOne("Leavemanagement.Repository.Entity.Employee", "Employees")
                        .WithMany("proofMappings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Leavemanagement.Repository.Entity.UserMapping", b =>
                {
                    b.HasOne("Leavemanagement.Repository.Entity.Employee", "Employee")
                        .WithMany("userMappings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leavemanagement.Repository.Entity.Roles", "Role")
                        .WithMany("userMappings")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Leavemanagement.Repository.Entity.Employee", b =>
                {
                    b.Navigation("leaveBalances");

                    b.Navigation("leaveRequestsAdmin");

                    b.Navigation("leaveRequestsEmployee");

                    b.Navigation("leaveRequestsHr");

                    b.Navigation("leaveRequestsManager");

                    b.Navigation("proofMappings");

                    b.Navigation("userMappings");
                });

            modelBuilder.Entity("Leavemanagement.Repository.Entity.Roles", b =>
                {
                    b.Navigation("userMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
